version: '2'
jobs:
  build:
    docker:
      - image: node:6.10.3-slim
    working_directory: ~/mastodon-following-list
    steps:
      - checkout
      - restore_cache:
          key: mastodon-following-list-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: twi4-app-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build Assets
          command: yarn build
      - run:
          name: Run Lint
          command: yarn lint
